#!/bin/bash

if [ ! -f "libBrownie.a" ] 
then
	make -f makefilestatic
fi

echo -n "Compiling test file ... "
rm *.o
rm *.exe
g++ test.cpp -static  -m32 -I"." -I"./ncl-2.0/src" -I"./TreeLib" -I"./TreeLib/gport" -I"c:\\Boost_Science_Package\\include" -L"." -L"c:\\Boost_Science_Package\\lib" -o test.exe -lgsl  -lgslcblas -lBrownie 

echo "done"



